[versions]
# Android SDK versions
android-cmdline-tools = "11076708"
compile-sdk = "36"
min-sdk = "21"
ndk-version = "28.2.13676358"
target-sdk = "36"

# App version
version-code = "2001102"
version-name = "2.0.11.2"

# External SDK versions
go_version = "1.25.4"

aboutLibraries = "13.1.0"
activity = "1.11.0"
android-material = "1.13.0"
android-gradle-plugin = "8.11.1"
compose-material3 = "1.4.0"
compose-material-icons = "1.7.8"
compose-ui = "1.9.4"
constraintlayout = "2.2.1"
core-ktx = "1.17.0"
dagger = "2.57.2"
documentfile = "1.1.0"
fragment-ktx = "1.8.9"
gson = "2.13.2"
guava = "33.5.0-android"
jbcrypt = "0.4"
kotlin = "2.2.21"
ksp = "2.3.2"
libsuperuser = "1.1.1"
lingala-zip4j = "2.11.5"
localbroadcastmanager = "1.1.0"
preference-ktx = "1.2.1"
recyclerview = "1.4.0"
stream = "1.2.2"
volley = "1.2.1"
zxing-android-embedded = "4.3.0"
# Do not upgrade zxing:core beyond 3.3.0 to ensure Android 6.0 compatibility.
zxing-core = "3.3.0"

[libraries]
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-material-icons" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
libsuperuser = { module = "eu.chainfire:libsuperuser", version.ref = "libsuperuser" }
lingala-zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "lingala-zip4j" }
localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "localbroadcastmanager" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
stream = { module = "com.annimon:stream", version.ref = "stream" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing-android-embedded" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing-core" }

[plugins]
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutLibraries" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
